<div id="eta_project">

{if is_foreachable($milestones)}

<table class="common" cellspacing="0">
<thead>
<tr>
<th>Milestone</th>
<th class="user">Responsabile</th>
<th>Tempo impiegato su tempo stimato</th>
<th>Percentuale completamento</th>
<th>Tempo rimanente</th>
</tr>
</thead>
<tbody>
{foreach from=$milestones item=object}
<tr>
<td>
	<a href="{assemble route='project_milestone' project_slug=$object->getProject()->getSlug() milestone_id=$object->getId()}">{$object->getName()}</a>
</td>
<td>
	{if $object->assignees()->hasAssignee()}
		<span class="details block">{user_link user=$object->assignees()->getAssignee()}</span>
	{else}
		---
	{/if}
</td>
<td>
{assign var=estimate_value value=$object->tracking()->getEstimate()->getValue()}
{assign var=summed_time_value value=$object->tracking()->sumTime($user)}
<span style="
{if $estimate_value lte $summed_time_value}
color: red;
{else}
color: green;
{/if}
	">
{$summed_time_value}h di 
	{if $object->tracking()->isEstimateAutogenerated()}
		<abbr title="Stima generata automaticamente">{$estimate_value}h</abbr>
	{else}
		<abbr title="Stima inserita dall'utente">{$estimate_value}h</abbr>
	{/if}
	
<span class="object_tracking" id="object_tracking_for_{$object->getId()}"></span>
<script type="text/javascript">
$('#object_tracking_for_{$object->getId()}').objectTime({
    object: {$milestone|json nofilter},
    show_label: false,
    default_billable_status: true
});
</script>
<img src="{image_url name="icons/12x12/edit.png" module=$smarty.const.ENVIRONMENT_FRAMEWORK}" class="icon_list_icon" alt="" />
</span>		
</td>

<td>
{if $object->getPercentsDone(false)}
{$object->getPercentsDone(false)}%
{else}
0%
{/if}
</td>
<td>
{if $object->getPercentsDone(false)}
{$object->getRemainingTime()}h
{else}
&#8734;
{/if} 
</td>
</tr>
{/foreach}
</tbody>
</table>	


{/if}

</div>
